### ISSUE TITLE
Add description text to sidebar

### ISSUE THREAD

**Issue by herbiemarkwort** [WazeDev/WME-FC-Layer#10]
It would be nice to have the ability to display information about the various state layers for the benefit of editors using this script. Information such as the data source, the kind of data the layer contains, the quality of the data, etc. One idea to display said data would be something like the ability to add following line of code to each state…

```javascript
info: [ { Source: 'Colorado DOT',
          Description: 'Please be extra cautious and consult with a state manager before using this data to set road types.' } ]
```
… which would produce text displayed in the sidebar underneath the state menu select like:

> **Source**
> Colorado DOT
> 
> **Description**
> Please be extra cautious and consult with a state manager before using this data to set road types.

**Comment by mapomatic** [comment]
Ask and ye shall receive... after ye do all the work to implement it yeself :)
